services:
  mongo:
    image: mongo
    container_name: sudoku-mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: sudokoop-server
    ports:
      - "5001:5001"
    environment:
      MONGODB_URI: "mongodb://mongo:27017/sudokoopDB"
      JWT_SECRET: "qualcosa_di_segreto"
    depends_on:
      - mongo

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: sudokoop-client
    ports:
      - "8080:8080"
    depends_on:
      - server

volumes:
  mongo_data: