name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Cache delle dipendenze del server
      - name: Cache server dependencies
        uses: actions/cache@v3
        with:
          path: |
            sudokoop/server/node_modules
          key: ${{ runner.os }}-server-${{ hashFiles('sudokoop/server/package-lock.json') }}
          restore-keys: ${{ runner.os }}-server-

      - name: Install server dependencies
        run: |
          cd sudokoop/server
          npm ci

      # Cache delle dipendenze del client
      - name: Cache client dependencies
        uses: actions/cache@v3
        with:
          path: |
            sudokoop/client/node_modules
          key: ${{ runner.os }}-client-${{ hashFiles('sudokoop/client/package-lock.json') }}
          restore-keys: ${{ runner.os }}-client-

      - name: Install client dependencies
        run: |
          cd sudokoop/client
          npm ci

  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Ripristina la cache server
      - name: Cache server dependencies
        uses: actions/cache@v3
        with:
          path: |
            sudokoop/server/node_modules
          key: ${{ runner.os }}-server-${{ hashFiles('sudokoop/server/package-lock.json') }}
          restore-keys: ${{ runner.os }}-server-

      - name: Test server
        run: |
          cd sudokoop/server
          npm test

  build:
    runs-on: ubuntu-latest
    needs: install  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Ripristina la cache client
      - name: Cache client dependencies
        uses: actions/cache@v3
        with:
          path: |
            sudokoop/client/node_modules
          key: ${{ runner.os }}-client-${{ hashFiles('sudokoop/client/package-lock.json') }}
          restore-keys: ${{ runner.os }}-client-

      - name: Build client
        run: |
          cd sudokoop/client
          npm run build
